spring:
  cloud:
    config:
      uri: http://locahost:8888
  
  application:
    name: order-ms
    
---

spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
          binder: rabbit
          destination: newpayment.ibm.exchange
          content-type: application/json
          group: ibmblr   
          
          
---
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0
          
    
server:
  port: ${PORT:${SERVER_PORT:0}}
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}} 
  